# Generated by Django 3.0 on 2019-12-29 15:23

import apps.api.invoicemanagement.utils
import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('street', models.CharField(max_length=50)),
                ('pin_code', models.CharField(max_length=10)),
            ],
            options={
                'db_table': 'address',
            },
        ),
        migrations.CreateModel(
            name='BuyerSeller',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('address', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='invoicemanagement.Address')),
            ],
            options={
                'db_table': 'buyerseller',
            },
        ),
        migrations.CreateModel(
            name='InvoiceDetail',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('invoice_number', models.CharField(max_length=20, null=True)),
                ('invoice_date', models.DateTimeField(null=True)),
                ('amount', models.FloatField(null=True)),
                ('buyer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='buyer', to='invoicemanagement.BuyerSeller')),
                ('seller', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='seller', to='invoicemanagement.BuyerSeller')),
            ],
            options={
                'db_table': 'invoicedetail',
            },
        ),
        migrations.CreateModel(
            name='UploadInvoice',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('user_id', models.IntegerField(default=11)),
                ('status', models.IntegerField(choices=[(0, 'New'), (1, 'InProgress'), (2, 'Done')], default=0)),
                ('creation_date', models.DateTimeField(default=datetime.datetime.now)),
                ('file_path', models.FileField(upload_to=apps.api.invoicemanagement.utils.get_file_path)),
                ('invoice_detail', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='invoicemanagement.InvoiceDetail')),
            ],
            options={
                'db_table': 'uploadinvoice',
            },
        ),
        migrations.CreateModel(
            name='InvoiceItem',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('quantity', models.IntegerField()),
                ('price', models.FloatField()),
                ('invoice', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invoice_item', to='invoicemanagement.InvoiceDetail')),
            ],
            options={
                'db_table': 'item',
            },
        ),
    ]
